version: '3.8'

services:
  database-local-test:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - "5439:5432"
    volumes:
      - database-data-test:/var/lib/postgresql/data

volumes:
  database-data-test:
